events {}

http {
  server {
    listen 80;

    location /pgadmin/ {
      proxy_pass http://pgadmin:80/;
    }

    location /mongo-express/ {
      proxy_pass http://mongo-express:8081/;
    }
  }
}
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}